name: passaround
description: An app to help you pass around text, files, and images, between your devices.
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  equatable: ^2.0.5
  flutter_bloc: ^8.0.0
  go_router: ^13.0.0
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.6
  dynamic_color: ^1.6.8
  firebase_auth: ^4.15.0
  super_drag_and_drop: ^0.8.0
  super_clipboard: ^0.8.0
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  url_launcher: ^6.2.2
  firebase_storage: ^11.5.6
  flutter_svg: ^2.0.9
  flutter_secure_storage: ^9.0.0

  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  bloc_test: ^9.1.0

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/