// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLBgN68GnkiWxOGSutmMcy7d9dA2eiIwA',
    appId: '1:653731631478:web:1193c817a92bb47d5c2a57',
    messagingSenderId: '653731631478',
    projectId: 'passaround-tcu',
    authDomain: 'passaround-tcu.firebaseapp.com',
    storageBucket: 'passaround-tcu.appspot.com',
    measurementId: 'G-FQW5VX70QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANMa7tNhUV4KWZAH1yGrIpsOfo5uKloX0',
    appId: '1:653731631478:android:ac04d2f3bca7ced75c2a57',
    messagingSenderId: '653731631478',
    projectId: 'passaround-tcu',
    storageBucket: 'passaround-tcu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZs86o2-vbTmVZWCYGI3a0YFZs2Y4_LS0',
    appId: '1:653731631478:ios:d2332874475c58795c2a57',
    messagingSenderId: '653731631478',
    projectId: 'passaround-tcu',
    storageBucket: 'passaround-tcu.appspot.com',
    iosClientId: '653731631478-c3kg93dokn21nqerfov7vn893vvcpt90.apps.googleusercontent.com',
    iosBundleId: 'io.thatcomeup.passaround',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZs86o2-vbTmVZWCYGI3a0YFZs2Y4_LS0',
    appId: '1:653731631478:ios:d2332874475c58795c2a57',
    messagingSenderId: '653731631478',
    projectId: 'passaround-tcu',
    storageBucket: 'passaround-tcu.appspot.com',
    iosClientId: '653731631478-c3kg93dokn21nqerfov7vn893vvcpt90.apps.googleusercontent.com',
    iosBundleId: 'io.thatcomeup.passaround',
  );
}
